---
-   name: Install ruby
    pacman: name=ruby state=present
-   name: Install puppet
    gem: name=puppet state=latest user_install=no

-   name: Add puppet user
    command: puppet resource group puppet ensure=present
-   name: Add puppet group
    command: puppet resource user puppet ensure=present gid=puppet shell='/sbin/nologin'

-   name: Create puppet directory
    file: path=/etc/puppet state=directory
-   name: Create puppet config
    template: src=puppet.conf.j2 dest=/etc/puppet/puppet.conf
-   name: Create temp directory
    copy: src=puppet.conf dest=/usr/lib/tmpfiles.d/puppet.conf

-   name: Fetch puppet service file
    get_url: >
        url='https://raw.github.com/puppetlabs/puppet/master/ext/systemd/puppetagent.service'
        dest=/etc/systemd/system/multi-user.target.wants/puppet.service
-   name: Force a systemd reload
    command: systemctl --system daemon-reload
...

