---
-   hosts: all
    gather_facts: no
    roles:
        - deploy
        - basic
        - kernel
        - puppet
        - { role: master, when: "'master' in group_names" }
    tasks:
        - name: Schedule the reboot
          command: shutdown
...

